name: Second Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some version on Ubunu
        run: node -v
  run-parallel-command:
    runs-on: windows-latest
    steps:
      - name: Display some version on Windows
        run: node -v
  run-second-command:
    runs-on: macos-latest
    needs: run-first-command
    steps:
      - name: Display some version on MacOs
        run: node -v
